"""Renders ``README.md`` from ``README.template.md``.

The template is plain Markdown with ``{{TOKEN}}`` placeholders, so the profile's
copy and layout can be edited without touching Python.  Everything the build
knows — asset paths, live counts, the generation timestamp — is exposed as a
token.

Image references are emitted with a content-hash query string.  GitHub serves
README images through its camo proxy, which caches aggressively; without the
hash a freshly regenerated SVG can keep showing the previous build for hours.
"""

from __future__ import annotations

import hashlib
import logging
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Mapping

LOGGER = logging.getLogger(__name__)

__all__ = ["ReadmeRenderer", "AssetReference"]

#: Matches ``{{TOKEN_NAME}}`` placeholders.
_TOKEN_PATTERN = re.compile(r"\{\{\s*([A-Z0-9_]+)\s*\}\}")

#: Comment blocks fenced by this marker are notes *for whoever edits the
#: template* and are stripped from the rendered README.
_TEMPLATE_ONLY_PATTERN = re.compile(
    r"<!--\s*TEMPLATE-ONLY.*?TEMPLATE-ONLY\s*-->\n*", re.DOTALL
)

#: Prepended to every generated README so nobody edits the wrong file.
_GENERATED_BANNER = """<!--
  ┌──────────────────────────────────────────────────────────────────────────┐
  │  DO NOT EDIT THIS FILE.                                                  │
  │                                                                          │
  │  README.md is generated from README.template.md by `python build.py`.    │
  │  Any change made here is overwritten by the next build — and by the      │
  │  scheduled workflow in .github/workflows/build-profile.yml.              │
  │                                                                          │
  │  Edit README.template.md (layout and copy) or profile.json (card copy).  │
  └──────────────────────────────────────────────────────────────────────────┘
-->
"""

#: Length of the cache-busting fragment appended to asset URLs.
_HASH_LENGTH = 10


@dataclass(frozen=True)
class AssetReference:
    """A generated SVG as the README should refer to it."""

    token: str
    path: Path
    relative_to: Path

    def to_url(self, *, cache_bust: bool) -> str:
        """Render the ``src`` value for this asset.

        Args:
            cache_bust: Append a content hash so GitHub's image proxy refreshes.

        Returns:
            A POSIX-style relative URL.
        """
        relative = self.path.relative_to(self.relative_to).as_posix()
        if not cache_bust:
            return relative
        return f"{relative}?v={self._content_hash()}"

    def _content_hash(self) -> str:
        """Short, stable hash of the asset's bytes."""
        digest = hashlib.sha256(self.path.read_bytes()).hexdigest()
        return digest[:_HASH_LENGTH]


class ReadmeRenderer:
    """Substitutes build tokens into the README template.

    Args:
        template_path: Source template.
        output_path: Destination README.
        cache_bust: Whether asset URLs carry a content hash.
    """

    def __init__(
        self, template_path: Path, output_path: Path, *, cache_bust: bool = True
    ) -> None:
        self.template_path = template_path
        self.output_path = output_path
        self.cache_bust = cache_bust

    def render(
        self,
        assets: Mapping[str, AssetReference],
        tokens: Mapping[str, str],
    ) -> str:
        """Produce the README text without writing it.

        Args:
            assets: Asset token name -> :class:`AssetReference`.
            tokens: Any further token name -> replacement text.

        Returns:
            The fully substituted Markdown.

        Raises:
            FileNotFoundError: If the template is missing.
        """
        template = self.template_path.read_text(encoding="utf-8")
        resolved: dict[str, str] = dict(tokens)
        for name, asset in assets.items():
            resolved[name] = asset.to_url(cache_bust=self.cache_bust)
        resolved.setdefault(
            "GENERATED_AT",
            datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        )

        missing: set[str] = set()

        def replace(match: re.Match[str]) -> str:
            name = match.group(1)
            if name in resolved:
                return resolved[name]
            missing.add(name)
            return match.group(0)

        rendered = _TOKEN_PATTERN.sub(replace, template)
        if missing:
            LOGGER.warning(
                "template referenced unknown tokens: %s", ", ".join(sorted(missing))
            )
        rendered = _TEMPLATE_ONLY_PATTERN.sub("", rendered).lstrip("\n")
        return f"{_GENERATED_BANNER}\n{rendered}"

    def write(
        self,
        assets: Mapping[str, AssetReference],
        tokens: Mapping[str, str],
    ) -> Path:
        """Render the README and write it to disk.

        Returns:
            The path written.
        """
        markdown = self.render(assets, tokens)
        self.output_path.write_text(markdown, encoding="utf-8")
        return self.output_path
